version: "3.9"

services:
  db:
    image: postgres:15
    container_name: intershop-postgres
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: intershop-redis
    restart: always
    ports:
      - "6379:6379"

  payment-service:
    image: eclipse-temurin:21-jre
    container_name: intershop-payment-service
    working_dir: /app
    volumes:
      - ./payment-service/build/libs:/app/libs:ro
    command: ["sh","-c","java -jar /app/libs/*.jar"]
    environment:
      SERVER_PORT: "8080"
      PAYMENTS_INITIAL_BALANCE: "50000"
    ports:
      - "8081:8080"
    restart: unless-stopped

  store:
    image: eclipse-temurin:21-jre
    container_name: intershop-store
    working_dir: /app
    volumes:
      - ./store/build/libs:/app/libs:ro
    command: ["sh","-c","java -jar /app/libs/*.jar"]
    environment:
      PAYMENTS_BASE_URL: http://payment-service:8080
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: "6379"
      SPRING_R2DBC_URL: r2dbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_R2DBC_USERNAME: ${POSTGRES_USER}
      SPRING_R2DBC_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      payment-service:
        condition: service_started
    restart: unless-stopped

volumes:
  pgdata:
