#Web
server.port=8080                    
server.servlet.context-path=/        

#Thymeleaf (templates connection) 
spring.thymeleaf.prefix=classpath:/templates/            
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false


spring.web.resources.static-locations=classpath:/static/,file:uploads/
 
#PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:intershop}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

#Hibernate 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Sql initialization 
spring.sql.init.mode=always

