server.port=${STORE_PORT:8081}
server.servlet.context-path=/
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.web.resources.static-locations=classpath:/static/,file:uploads/
spring.r2dbc.url=r2dbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.r2dbc.username=${POSTGRES_USER}
spring.r2dbc.password=${POSTGRES_PASSWORD}
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
payments.base-url=${PAYMENTS_BASE_URL} 
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.repositories.enabled=false
# --- OAuth2 Client Credentials (payment-client) ---
spring.security.oauth2.client.registration.payment-client.client-id=${CLIENT_ID}
spring.security.oauth2.client.registration.payment-client.client-secret=${CLIENT_SECRET}
spring.security.oauth2.client.registration.payment-client.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.payment-client.scope=${CLIENT_SCOPES}
spring.security.oauth2.client.provider.payment-provider.token-uri=${TOKEN_URI}
