server.port=${PAYMENT_PORT}
server.servlet.context-path=/
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
spring.web.resources.static-locations=classpath:/static/,file:uploads/
spring.r2dbc.url=r2dbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.r2dbc.username=${POSTGRES_USER}
spring.r2dbc.password=${POSTGRES_PASSWORD}
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
payments.initial-balance=${PAYMENTS_INITIAL_BALANCE}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${ISSUER_URI}
