server.port=${SERVER_PORT:8080}
server.servlet.context-path=/
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
spring.web.resources.static-locations=classpath:/static/,file:uploads/
spring.r2dbc.url=r2dbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:intershop}
spring.r2dbc.username=${POSTGRES_USER:postgres}
spring.r2dbc.password=${POSTGRES_PASSWORD:postgres}
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
payments.initial-balance=${PAYMENTS_INITIAL_BALANCE:50000}